### ISSUE TITLE
descriptionPadding not working

### ISSUE THREAD

**Issue by dnestico** [Pyozer/introduction_screen#165]
I do not understand why it is not letting me use the "descriptionPadding" PageDecoration option, I have a body defined on each PageView so why is "descriptionPadding" not working? Pls help a noob who's just learning flutter now.

**Can't use "descriptionPadding" for some reason**

**To Reproduce**
1. Put a body in the PageView
2. Add "descriptionPadding" to PageDecoration
3. See error

**Expected behavior**

I'm just expecting "descriptionPadding" to work, I am watching a tutorial and his works just fine, I even copied his just to test and it didn't work for me also with his own code.

**Screenshots**

![Screen Shot 2023-02-01 at 1 45 36 AM](https://user-images.githubusercontent.com/3034555/215971183-21d0d884-e686-401e-b589-b9c2982b53e5.png)
![Screen Shot 2023-02-01 at 1 46 21 AM](https://user-images.githubusercontent.com/3034555/215971291-fdb7edf2-6b5f-4691-85ca-8547d43b17de.png)
![Screen Shot 2023-02-01 at 1 46 41 AM](https://user-images.githubusercontent.com/3034555/215971343-b3857050-8a89-451f-b7d8-4599bd507ff8.png)

**Smartphone (please complete the following information):**
- IOS Simulator
- IOS 15.0
- Version [e.g. if applicable]

**Additional context**

**Comment by ghenry** [comment]
Hi @dnestico 

I've had a look through the code base (I just maintain this project) and can see this:

https://github.com/Pyozer/introduction_screen/pull/73

_"I also renamed `descriptionPadding` to `bodyPadding` since it was only used for setting the body padding and nothing else."_

So I'd say this is a documentation bug. It is mentioned:

https://github.com/Pyozer/introduction_screen/blob/53933546f66cfe35dc0c72d9cd2dbea737a1ff61/lib/src/model/page_decoration.dart#L114

and

https://github.com/Pyozer/introduction_screen/blob/53933546f66cfe35dc0c72d9cd2dbea737a1ff61/lib/src/model/page_decoration.dart#L138

but it's not in the main class initialisation params.

Can you try `bodyPadding` and see if that does what you're after? I'll then clear up the docs etc.

Thanks.

**Comment by dnestico** [comment]
@ghenry Thank you! I will try this out later tonight and let you know, sorry for late reply.

**Comment by dnestico** [comment]
Thank you this appears to have worked!

If you don't mind, I have another question about the pageColor and if it is possible to make it follow the device theme like it is possible to make the globalBackgroundColor follow the theme.

My code:

` globalBackgroundColor: Theme.of(context).primaryColor, `

` pageColor: Colors.transparent, `
