### ISSUE TITLE
How can i pass data between pageviewmodels ?

### ISSUE THREAD

**Issue by thinhhoangnguyen** [Pyozer/introduction_screen#44]

**Comment by Pyozer** [comment]
Hi, sorry for my very late reply :/
Hope you have found a solution.

This package is not quite designed for this sorry. In next release (very soon available) you will be able to set `rawPages` (List<Widget>) param instead of `pages` (List<PageViewModel>). I think you can do something with this.

I close this issue, if you have another question for this issue, re-open it ;)
